### ISSUE TITLE
print-pdf broken ?

### ISSUE THREAD

**Issue by dbaeli** [lesfurets/lesfurets-conferences#1]
Adding "?print-pdf" at the end of the url should display the one page version.
Is this broken or no more supported ?

**Comment by apflieger** [comment]
seems so, it might be the custom theme

**Comment by dubreuia** [comment]
I corrected the missing CSS so the print-pdf works, but the layout is broken. It should be supported and used to work on the lesfurets theme.

**Comment by apflieger** [comment]
PDF export mandatory for devoxx ...

**Comment by dubreuia** [comment]
Fixed it, you need chromium / chrome and then you do "print > print to pdf"
